#  ______         _ _ _      _____
# |  ____|       (_) (_)    / ____|
# | |__ __ _  ___ _| |_ ___| |     ___  _ __ ___  _ __ ___   ___  _ __
# |  __/ _` |/ __| | | / __| |    / _ \| '_ ` _ \| '_ ` _ \ / _ \| '_ \
# | | | (_| | (__| | | \__ \ |___| (_) | | | | | | | | | | | (_) | | | |
# |_|  \__,_|\___|_|_|_|___/\_____\___/|_| |_| |_|_| |_| |_|\___/|_| |_|
#
# Copyright (c) 2023 by Dev7ex
# Version: ${project.version}
# Software: Bukkit
config-version: ${project.version}
# General
prefix: '§8[§cFacilisCommon§8]§r'
no-permission: '§cIm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that is in error.'
# Settings
settings:
  receive-update-message: true
  update-message-player: '%prefix% §7There is a new update available. §8[§chttps://www.spigotmc.org/resources/faciliscommon.107198/'
  update-message-version-player: '%prefix% §7Current Version: §c%current_version% §7New Version §c%new_version%'

